### PR TITLE
Clean up site for end of event

### PR DESCRIPTION
**Pull request by zanedb**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Nice work here @zanedb. Can we move our pages intact to a folder though? A bunch of times I’ve wanted to refer back to Hack Chicago or someone’s site & having it gone is really frustrating. Of course we’re not looking for a PennApps-style site but I like how you can get back to stuff.

**Comment by zanedb** [comment]
I could make a new repo and put all our old files at 2018.hackpenn.com maybe? Or just move them to hackpenn.com/2018/whatever. Thoughts?

**Comment by lachlanjc** [comment]
It happened in 2019, but that’s tough since idk the calendar year of the next event

**Comment by zanedb** [comment]
Sorry, I meant 2019. Still living in 2018 haha

How does the hackpenn.com/2019 approach sound for right now? If we run another event later this year, we can always update it to be /spring or something.

**Comment by zanedb** [comment]
Ok, so I've renamed this repo to `2019-site`, and it is now deploying at 2019.hackpenn.com. I made a new repo with these changes applied at `site`, which deploys live at hackpenn.com. Should fix the problem for now at least.

Closing this PR because changes have been applied in the `site` repo.

**Pull request closed without merging**
